[application]
name = "Arc Raiders Companion App"
android_manifest = "android/AndroidManifest.xml"

[bundle]
identifier = "com.arcraiderscompanionapp"
publisher = "Dakota-Lewis"
icon = ["assets/img/Logo.webp"]

[web.app]

# HTML title tag content
title = "arc-raiders-companion-app"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []
